version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
clone_depth: 5
before_build:
- cmd: nuget restore -PackagesDirectory packages
build:
  project: Translator.sln
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: zbtoh4Gg7JoD7zFiEbv4txr4rjfCawpmeRJ/FfxO7u9VjZpLzh6T392ze8TEwaMV
  prerelease: true
skip_commits:
  files:
    - README.*
    - .gitattributes
    - .gitignore
